CREATE TABLE IF NOT EXISTS aqi_history (
  id STRING DEFAULT GENERATE_UUID(),
  zone STRING NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  aqi_value FLOAT64 NOT NULL,
  source_status STRING NOT NULL,        -- 'ok' | 'stale' | 'failed'
  confidence_penalty FLOAT64 DEFAULT 0.0,
  raw_payload_uri STRING,               -- pointer to Cloud Storage raw object
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY DATE(timestamp)
CLUSTER BY zone;

CREATE TABLE IF NOT EXISTS weather_history (
  id STRING DEFAULT GENERATE_UUID(),
  zone STRING NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  temperature_c FLOAT64,
  humidity_pct FLOAT64,
  wind_kph FLOAT64,
  source_status STRING NOT NULL,        -- 'ok' | 'stale' | 'failed'
  raw_payload_uri STRING,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY DATE(timestamp)
CLUSTER BY zone;

CREATE TABLE IF NOT EXISTS complaints_history (
  id STRING DEFAULT GENERATE_UUID(),
  zone STRING NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  raw_text STRING NOT NULL,
  category STRING,                      -- e.g. 'respiratory', 'visibility', 'odor'
  severity STRING,                      -- 'low' | 'medium' | 'high' | 'very_high'
  cluster_id STRING,                    -- set by Triage Agent's cuML clustering step
  is_simulated BOOL DEFAULT TRUE,       -- explicit flag per the project's data honesty statement
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY DATE(timestamp)
CLUSTER BY zone;

CREATE TABLE IF NOT EXISTS forecasts (
  id STRING DEFAULT GENERATE_UUID(),
  zone STRING NOT NULL,
  generated_at TIMESTAMP NOT NULL,
  predicted_aqi FLOAT64 NOT NULL,
  horizon_hours INT64 NOT NULL,
  confidence FLOAT64 NOT NULL,
  reasoning STRING,
  is_whatif BOOL DEFAULT FALSE,         -- true if generated by the what-if simulator, not a scheduled run
  whatif_params JSON,                   -- e.g. { "traffic_multiplier": 1.2 }
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY DATE(generated_at)
CLUSTER BY zone;

CREATE TABLE IF NOT EXISTS agent_decisions_log (
  id STRING DEFAULT GENERATE_UUID(),
  agent_name STRING NOT NULL,           -- 'ingestion' | 'forecast' | 'triage' | 'decision' | 'reflection' | 'human' | 'notification'
  zone STRING,
  timestamp TIMESTAMP NOT NULL,
  action STRING NOT NULL,               -- short human-readable action, e.g. "Detected complaint spike, escalating"
  input_ref STRING,                     -- id/reference to the input this agent acted on
  output_json JSON,                     -- full structured output for this agent step
  conflict_flag BOOL DEFAULT FALSE,
  escalation_flag BOOL DEFAULT FALSE,
  confidence FLOAT64,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY DATE(timestamp)
CLUSTER BY agent_name, zone;

CREATE TABLE IF NOT EXISTS decisions (
  id STRING DEFAULT GENERATE_UUID(),
  zone STRING NOT NULL,
  generated_at TIMESTAMP NOT NULL,
  risk_level STRING NOT NULL,           -- 'low' | 'medium' | 'high' | 'severe'
  overall_confidence FLOAT64 NOT NULL,
  conflict_detected BOOL DEFAULT FALSE,
  recommendations JSON NOT NULL,        -- array of { target, action }
  rationale STRING,
  reflection_id STRING,                 -- FK-equivalent reference to reflections.id
  approval_status STRING DEFAULT 'pending', -- 'pending' | 'approved' | 'rejected'
  reviewer_id STRING,
  reviewed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY DATE(generated_at)
CLUSTER BY zone;

CREATE TABLE IF NOT EXISTS reflections (
  id STRING DEFAULT GENERATE_UUID(),
  decision_id STRING NOT NULL,
  validated BOOL NOT NULL,
  requires_human_review BOOL NOT NULL,
  flags JSON,                           -- array of strings, e.g. ["low_confidence", "stale_weather_data"]
  notes STRING,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY decision_id;

CREATE TABLE IF NOT EXISTS notifications_log (
  id STRING DEFAULT GENERATE_UUID(),
  decision_id STRING NOT NULL,
  zone STRING NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  target_audience STRING NOT NULL,      -- 'schools' | 'hospital' | 'transit' | 'citizens'
  message STRING NOT NULL,
  approved_by STRING,
  dispatch_status STRING DEFAULT 'simulated', -- 'simulated' | 'sent' | 'failed'
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY DATE(timestamp)
CLUSTER BY zone;
