-- CityPulse AI — forecasts table
-- BigQuery Standard SQL DDL
-- See docs/DATABASE_SCHEMA.md
-- Note: Not in original TRD table list but needed to persist Forecast Agent output

CREATE TABLE IF NOT EXISTS forecasts (
  id STRING DEFAULT GENERATE_UUID(),
  zone STRING NOT NULL,
  generated_at TIMESTAMP NOT NULL,
  predicted_aqi FLOAT64 NOT NULL,
  horizon_hours INT64 NOT NULL,
  confidence FLOAT64 NOT NULL,
  reasoning STRING,
  is_whatif BOOL DEFAULT FALSE,         -- true if generated by what-if simulator
  whatif_params JSON,                   -- e.g. { "traffic_multiplier": 1.2 }
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY DATE(generated_at)
CLUSTER BY zone;
