import { decide, resolveConflict } from "../src/lib/agents/decision-agent";
import type { ForecastOutput, TriageOutput } from "../src/lib/types/agent-schemas";
import crypto from "crypto";

async function runPhase3Tests() {
  console.log("=== Starting Phase 3 Decision Agent Tests ===\n");

  console.log("1. Seeding Deliberately Conflicting Scenario...");
  
  // Fake forecast (Tier 0 - Low)
  const fakeForecast: ForecastOutput = {
    zone: "Zone-A",
    predicted_aqi: 45,
    horizon_hours: 24,
    confidence: 0.9,
    reasoning: "Weather conditions and historical trends indicate clear air.",
  };
  console.log("   Forecast AQI:", fakeForecast.predicted_aqi);

  // Fake triage (Tier 3 - Very High)
  const fakeTriage: TriageOutput = {
    zone: "Zone-A",
    complaint_count: 55,
    trend_vs_yesterday: "up",
    severity_signal: "very_high",
    hotspot_detected: true,
    summary: "Massive spike in citizen reports of severe respiratory distress.",
  };
  console.log("   Triage Severity:", fakeTriage.severity_signal);

  console.log("\n2. Executing Decision Agent...");
  const decision = await decide(fakeForecast, fakeTriage, "Zone-A");
  
  console.log("   Conflict Detected:", decision.conflict_detected);
  if (!decision.conflict_detected) {
    throw new Error("Conflict detection failed! Low forecast vs Very High triage should trigger conflict.");
  }
  
  console.log("   Final Computed Risk Level:", decision.risk_level);
  console.log("   Overall Confidence:", decision.overall_confidence);
  console.log("   Rationale generated by Gemini:");
  console.log(`      "${decision.rationale}"`);

  console.log("\n3. Executing Supplementary-Data Conflict Resolution Round-Trip...");
  const conflictId = crypto.randomUUID();
  const resolvedDecision = await resolveConflict("Zone-A", conflictId);
  
  console.log("   Conflict Detected (Resolved):", resolvedDecision.conflict_detected);
  if (resolvedDecision.conflict_detected) {
    throw new Error("Conflict was not resolved! `resolvedWithNewData` logic failed.");
  }

  console.log("   Final Computed Risk Level (Resolved):", resolvedDecision.risk_level);
  console.log("   Resolved Rationale generated by Gemini:");
  console.log(`      "${resolvedDecision.rationale}"`);

  console.log("\n=== Phase 3 Tests Passed Successfully! ===");
}

runPhase3Tests().catch((err) => {
  console.error("\n*** Test execution failed: ***", err);
  process.exit(1);
});
